In [2]:
import torch

In [4]:
A = torch.arange(15, dtype=torch.float32).reshape(3, 5)
A

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [12]:
A.sum(dim=1)

tensor([10., 35., 60.])

In [20]:
A.numel()

15

In [23]:
B = torch.ones((2, 3, 4))
B

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [27]:
B / B.sum(axis=1, keepdim=True)

tensor([[[0.3333, 0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333, 0.3333]],

        [[0.3333, 0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.3333, 0.3333, 0.3333, 0.3333]]])